use env read mirror url
AspadaX/RustyFace pull request #3
Opened 2024-08-15 03:55 UTC by asamaayako

从环境变量读取镜像地址 如果不存在 使用默认的huggingface.  行为模仿常用的huggingface下载工具

2024-08-15 05:42 UTC, AspadaX requested changes
Great thanks to your change. I think this is a practical feature. 
Would it be nice to use `https://hf-mirror.com/` instead of the HuggingFace official url as the default? The mirror site is accessible globally.

2024-08-15 05:51 UTC, asamaayako commented
> 非常感谢你的修改。这个功实用。 使用 `https://hf-mirror.com/` 作为默认地址而不是 HuggingFace 的官方 URL 会不会更好呢？这个镜像站点在全球都可以访问。大陆网络环境你懂的。
> 
> Great thanks to your change. I think this is a practical feature. Would it be nice to use `https://hf-mirror.com/` instead of the HuggingFace official url as the default? The mirror site is accessible globally.

我希望这个工具和大部分的工具行为接近或一致。 使用`https://hf-mirror.com/`做默认地址与大部分的模型下载工具有点不太一样。如果你觉得应该使用`https://hf-mirror.com/`做默认更好直接修改就可以了的🤞

2024-08-15 14:45 UTC, AspadaX approved these changes

2024-08-15 14:45 UTC, merged

2024-08-23 07:27 UTC, AspadaX commented
@all-contributors
please add @AspadaX  for "kickstarting this project".
please add @asamaayako  for "further optimized the project's features".

2024-08-23 07:30 UTC, AspadaX commented
@all-contributors
please add @asamaayako for "further optimized the project's features".